site_name: BlueCloud Cyber Range 
repo_url: https://github.com/iknowjason/BlueCloud
repo_name: iknowjason/BlueCloud
nav:
   - Home: index.md
   - Use Cases: usecases.md
   - Features: features.md
   - Credentials : infrastructure.md
   - Remote Access : remoteaccess.md
   - Azure Install : azureinstall.md
   - AWS Install : awsinstall.md
   - APT Simulation : apt.md
   - References : references.md
   - Credits : credits.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tabs
  font:
    text: Roboto
  palette:
    # Light mode
    - green: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue 
      accent: blue 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode test
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
