---
- name: Execute Invoke-Atomic powershell script for Atomic Red Team
  win_shell: powershell.exe Invoke-AtomicTest T1021.006 -PathToAtomicsFolder C:\terraform\ART\atomic-red-team-master\atomics
  args:
    executable: cmd
  register: results

- debug:
    var: results.stdout_lines
