version:
  name: velociraptor
  version: 0.5.6
  commit: "2715027"
  build_time: "2021-02-08T20:10:52+10:00"
Client:
  server_urls:
  - https://10.100.1.5:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDKjCCAhKgAwIBAgIQYnOxXVwB4n05CnFT1rn6qDANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjEwNDA5MDExNTU3WhcNMzEw
    NDA3MDExNTU3WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDTm+VYUE1aE/4FwgdXDYvCUxSiydIW0biU
    zyS1gG4cDkR+NvYueiXtFZ8KjzJGQuZvlD+2g1zuMUbQnD9qsxET5hcsHd8qmCBx
    EhVxPde4wpc6prudAVqC8qqGN1NQvLOcI8lJqwwtk/OqMENbOK2QLueD3FLVPVO/
    +5WGh1193JupoFcrrZjfNjbARYsxUSCfk0mLfyDk1a0BSn4I0rr6SSb80QhPjY3P
    DRZLkaHyNgSIlUKW3JmlpJ1ftRsyzgFSUIW2vJcVzHCew/4xT3Gxou3oteTdfcoa
    BtKVxd0GotaI81qamxcsOR6D615kaq/PJ6GufXG/SYbpkwWIYUCJAgMBAAGjbDBq
    MA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
    DwYDVR0TAQH/BAUwAwEB/zAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVs
    b2NpZGV4LmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAJGB8Hrdg8k/ks6mehH1yZvWs
    fMrmB43rcJehropWCtjniV/Nic3xxL84M1JPPkcARUg+67J2BMz/HDL92JrPxa5p
    q8k+Hfs+NbPLU74cd92X2oUCrnMUM3KMJOb0lKpvhaGFau6K2aFCpPTBwNc9nSIZ
    D2DNZjVgWwmz7eN1M6F02r0CWe3yi5o7nKMMKnzP56tOG4ZBmJ0th7VhLIbvbwzJ
    mrn8qLi7uB8bVHci7gCY0HdksG4mMowK3pPcrF0KbLQ6sUDdGTpN/+jqR3P9ekvf
    dcmz2RnFaVrRhYoz/8AK8ImrflCgwO79JJ/LR52GEKPkZvYP7pTgYSBvYNrcDg==
    -----END CERTIFICATE-----
  nonce: G0fs0eFFVPE=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.5.6
    commit: "2715027"
    build_time: "2021-02-08T20:10:52+10:00"
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  bind_address: 10.100.1.5
  bind_port: 8001
  bind_scheme: tcp
  pinned_gw_name: GRPC_GW
GUI:
  bind_address: 10.100.1.5
  bind_port: 8889
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDITCCAgmgAwIBAgIRAM3LLudfWsV5RjESA8Z1q4gwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIxMDQwOTAxMTU1OFoXDTIy
    MDQwOTAxMTU1OFowKTEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRAwDgYDVQQDDAdH
    UlBDX0dXMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1gvGvp8qjsCG
    l5D9BYI0MjlbE7Zm5+hYKjRihw6BGHcgJ8cf9ceS8XsV1C23MOLBUTjTRKHOIJks
    VjtSrWnYnObPIWu5YNwLN7oqCXDaHgDUQBZzf8Xm854+9tFnMslZJprpsefvc8w6
    5STiGbCpS7DovNMRfhyag/j8I1hQgW+Xi5bGjN7p+5w5gww2ZQ+F2PwJ2fZXyJws
    KrcGvjPX11qNLij90nUabPhOtAHzbY2mC9rFt3sBa6IRn4AOOvhYO2gCcjp8UUky
    kfrNMfuOGfPQcR5NHlXnNiFlyeT9DrnCfhTQgKN0jRL6TG6E86h6H4q9xoz7atjm
    rKtox8p6GwIDAQABo1MwUTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
    BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwEgYDVR0RBAswCYIHR1JQQ19H
    VzANBgkqhkiG9w0BAQsFAAOCAQEAMoE1OSNMtjFNVAXw0H+pdiZYkuzw1C6mMV8w
    EwMoJR3WqHFIYh1EKLWMYSXVleH77jLDS+y36ra9gVKi0pBnzxeAAFElhpqWjAqy
    1LHozqb+jfNfjGmZIiNt8RHM46jNe/5+MOkYTV84TJRKI1LFnpHB6O5HOpb9ghlJ
    usvo1xZ/BjcOBlKFy3TLvnT6/3A+ZxRbobsywG15/ASp/ODVz7K99r36u/h7lFoq
    bL2PpnOAigFgNTPrYfYiOu6vbiRNY7VFOkJdTAesYxOGcAJ8IaaMQQkRoPfktdxh
    WQJ6AuR7671jJ1YAihL4Fgwg/FSy3gi7VQw0upMAOVPuDEqh4Q==
    -----END CERTIFICATE-----
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA1gvGvp8qjsCGl5D9BYI0MjlbE7Zm5+hYKjRihw6BGHcgJ8cf
    9ceS8XsV1C23MOLBUTjTRKHOIJksVjtSrWnYnObPIWu5YNwLN7oqCXDaHgDUQBZz
    f8Xm854+9tFnMslZJprpsefvc8w65STiGbCpS7DovNMRfhyag/j8I1hQgW+Xi5bG
    jN7p+5w5gww2ZQ+F2PwJ2fZXyJwsKrcGvjPX11qNLij90nUabPhOtAHzbY2mC9rF
    t3sBa6IRn4AOOvhYO2gCcjp8UUkykfrNMfuOGfPQcR5NHlXnNiFlyeT9DrnCfhTQ
    gKN0jRL6TG6E86h6H4q9xoz7atjmrKtox8p6GwIDAQABAoIBAQCSlF32DGnIeG+z
    O8cKDrBP9Jc6WJ8AEUzPGjCe7H/bkTikBOkOFy250OCR/PyGrcJVLOUBCw1tpXeH
    Vfi4aNO+HxGZgXvhqM7Fyucer/muskKn4LgXuB8Alk3oGF7jmJ9EoLGI85w3YJS0
    dx2fGivVecDoDmLcShpGZivEyKXY/KGkCjDxWXH7Ybdm25WCuQADqPaewXLeTbDH
    pJWHulgEPK+JzbVK5N18N1H4QIGdPMSRji+ORfZkcTOnE27jcB7zUfZt9lwyaAEq
    ziXkhpOWmULSR4pBBrzImFqqQJdno0jQHXKJmGcIiFNJDGg/cD5AJ/kCrtZUTnjs
    oCvOP3QBAoGBAPMitvl37Gi30w9yOP0Tk3snaFB41yOgGPux25OcpU7nfGcryJxo
    /SRHz8gfguQnRFUFt2PfAUeya9UdrcbZt/dzvv3jNmdmXqG13F6sM2t8Vsr3WM6i
    wXWeUSbXQIlh6Roz4d0D+cLJpbLSAiXeTsOyqA4c8CBcxnJe60LC/yw7AoGBAOFf
    CpOEx5dS0tKVmXk2wJEOQG5oAxWtTPuZUTLPU8LmE1W0RNLOWbRtgSeqkYfCDUDh
    KPFtNPnS58sESnEMkAoO15lSbxQL1tUE6yLwfcx6IQdq7WWcEJPSSRAdG6KhQS9v
    TvRcBMYcO2F7J7t3xw/dA/IiZ1KYT+RQhyaTSWuhAoGAMaGKfE4woge0O9jzLSYL
    2v3mW1bvg8QwlWBvFCjLzdmPGXhkkRkVY4yNK6rTC0PAvSJXlzl0h3AyduSCDq9u
    0EJ+YFE7T8wj0RrQizrXnD9bcD8hj7zFhP72TdluwRyNet3QY09mco67Fk+sRJKm
    vWgAyjC6C8EkeUBLAevQLvUCgYAVasbChhfBlalbQcQ39LAQGN6en1vLr5BlSIii
    33kCSIMF3f+8WMfFkbJ4Zok18Yb452zQpKQoKZbFgD7ix2LY0dhDRcYwjX949uKx
    i1EpIWIKJmsxAMfChHVVBq8doV1keJt0NVpuyTgLZ3y7IALWyxYY6JQREVBmThDJ
    5a1QgQKBgQCLs3hP7MX3fLt7sClRHYsxiM2jVblDpIZltic3inoHCn893v0q1XqD
    LfqYUZE35AM9YKq7u6GcI7G/GYnBj6fJ0I0ZgCb47eUAQ6zgfL7r7nj8eTH6tkQX
    XSAubg3dJlCtz173xZNBJhjO0MlNF1z4/WAII1iS8Rzr/E52SqsMRw==
    -----END RSA PRIVATE KEY-----
  internal_cidr:
  - 127.0.0.1/12
  - 192.168.0.0/16
  authenticator:
    type: Basic
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA05vlWFBNWhP+BcIHVw2LwlMUosnSFtG4lM8ktYBuHA5Efjb2
    Lnol7RWfCo8yRkLmb5Q/toNc7jFG0Jw/arMRE+YXLB3fKpggcRIVcT3XuMKXOqa7
    nQFagvKqhjdTULyznCPJSasMLZPzqjBDWzitkC7ng9xS1T1Tv/uVhoddfdybqaBX
    K62Y3zY2wEWLMVEgn5NJi38g5NWtAUp+CNK6+kkm/NEIT42Nzw0WS5Gh8jYEiJVC
    ltyZpaSdX7UbMs4BUlCFtryXFcxwnsP+MU9xsaLt6LXk3X3KGgbSlcXdBqLWiPNa
    mpsXLDkeg+teZGqvzyehrn1xv0mG6ZMFiGFAiQIDAQABAoIBABmtANcGZ1xWsKvi
    LyHQ8vRRQF/APU2nhM4JlFqxiqq80HLAGH7rM07hILsXRPJhi7ReOJzcs5nzQLRv
    QQKhV6Eieg1QUpPIgac2moNzDYnNkqv7LyiN0X2yFB7U97cELobzkKjvqDqfiSFN
    Wd7nsaedCVpmkWZuWosg67O3GRD8SyTOPrOAKJ/XyRZHBYLTBbUKJxuoOZxd4dzM
    ZAFEZbASNVuD9XO65D33gRIGW9QS72bqmQnGyy011CoVOEq/sfR933jcdgwfycsF
    XvFqpv6nOdTpfWlmyKIErgpuAoccBev96SQawr7EY6rg8UoGv2OvrONd2Stdm9hr
    vDPLXUECgYEA4cmxfs/49AACZTD8aS3oSS4u2sWg0I/0VfG4BHqx0uFgvTlXY8hM
    dzsLHUoR54OubPAlbYh4HFZxQmg4rZIt2bdfV+aZQdtZsfewRUZTZxaAqDrkcYj8
    qD28xHW+cTQNYJI8khZrGWKhykcqzx2/uLIAo48sCnln9HPDeS67HbcCgYEA7+yC
    DFOAOsNf1DKQ3bRTcr2hVmBqw5Bjtwn2YGQivjsqK4LJ9zXb37GBOyVQ7JMkEVrR
    s288JykNMcMo6DhR95EpMjtoY+O5owE+q06aayS4Z8yd3dxab1sWi1Iesr2DA1sI
    hHWjqo0YidSONERZRyHReBnSSZ2+UFWhjmz6k78CgYBQc8XDIefbSYWQ+Pt3ntv9
    927KlVDP//tYBGFFd1KViakmw5/X9i8I7QjwzsvCarFkL82mUdI6hrKkru5DKqsb
    wLNAZvKE/NvhBhjRFlXxjZsaVqG/ssgUSqtQdYP+YkXB+1mJ1GMlEHgF04X1duwx
    q3t+zC0tLkVUXUtxiq0x0QKBgE7Smcso57jmlSYm0rcz1jKdIFM7a/gCCPCKoln6
    q/tpfqo61tWT6T+tlnJzCQogMTpOZxSXV+DZuM7/egII9szp8Oni4KHooAVwlEE9
    mrfWoYrgi4DnMwLgnyB4g0NfxZolnz+9Ul7m6gfmQC3lwpr+/k2B1jd/TpYf++rJ
    3O0LAoGBAM0b4bJLmkuoItHwkygK1FYXmmuxUMo/sANfa+n11drOz1+Dp/wWt2vo
    JUbPux54uAm9RW99QMWcMEVGwCr6efftwitYEzcLX0m4xDXPq2mZDvtYpwJe/ylu
    SoUtXgpkvmfR0hAH90Kq7GHEF9E3FPJDp+/4FpKPdtt8RLHeTuSH
    -----END RSA PRIVATE KEY-----
Frontend:
  hostname: localhost
  bind_address: 0.0.0.0
  bind_port: 8000
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDNzCCAh+gAwIBAgIRAJszxTehv9AJ2rqsoXAG8+YwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIxMDQwOTAxMTU1N1oXDTIy
    MDQwOTAxMTU1N1owNDEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRswGQYDVQQDExJW
    ZWxvY2lyYXB0b3JTZXJ2ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDIh85vuISB2DNPkWKy8Plo7ItnzfQFML/PfVfzCrtUoam2o455Di2fnQZ6TG4E
    WmTg3kqynu3NJ+9roX/hqP0/mZuAUR6nzjklVXNDbuH44L4MfUfNmDjXwwxEt1lE
    3ZlgTI8GnUG2gOCl6d7OOQ0BfEN8EB5CFoCQA4KltdbFFdsoRu1kYYMNCNGAh4zV
    jYghcpqDYTpGyGauSRdTI69gZm2N+h1EHI8yQH/8XvbTB9L3EcZkrUSbIgXiHzHP
    jQZm11DjiJnncVEd1qYqcDlQK+d7Pu3wV5dvljpyYPoWKTeqbdZ+ynpU/RaYYNdd
    NgxXY5vGM7P5UT8bHtUSHMsDAgMBAAGjXjBcMA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHREE
    FjAUghJWZWxvY2lyYXB0b3JTZXJ2ZXIwDQYJKoZIhvcNAQELBQADggEBAHkHvwtc
    T75ZPDL7CE4cnQ6WFajYcGqED+BiMeC06TLT9CxFH4lOy3Gj97imej+dtxWeAZ4L
    VZnml0yVFoJ98qgepQZ+FyPZeWSno1awMOfAg0C4SuBi+98Gd+gpJK1RFd02PrfO
    Qp5V0rNyKodUedmPXeKbTcYOsOlrVYxZRyYRu+VUhha1waRLjoJKWt9DO+Kpe6ss
    pNxYiRHAu4bIPaHHcJveWsRMG8KdA5oe5nlqsPbTrHqEICK/vrDYM95kgZRfIONM
    IZp+Y7bLWTrdOJAKCZAIsC9ZfCEdwHLdvcN7cu5/Iwpiupfi5Iv4+RcSQLxu0Gyj
    ndHVIasiGuMKV4M=
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAyIfOb7iEgdgzT5FisvD5aOyLZ830BTC/z31X8wq7VKGptqOO
    eQ4tn50GekxuBFpk4N5Ksp7tzSfva6F/4aj9P5mbgFEep845JVVzQ27h+OC+DH1H
    zZg418MMRLdZRN2ZYEyPBp1BtoDgpenezjkNAXxDfBAeQhaAkAOCpbXWxRXbKEbt
    ZGGDDQjRgIeM1Y2IIXKag2E6RshmrkkXUyOvYGZtjfodRByPMkB//F720wfS9xHG
    ZK1EmyIF4h8xz40GZtdQ44iZ53FRHdamKnA5UCvnez7t8FeXb5Y6cmD6Fik3qm3W
    fsp6VP0WmGDXXTYMV2ObxjOz+VE/Gx7VEhzLAwIDAQABAoIBAFhxlXou7rp6Cb95
    RwfXQpmlYqLo8kxrwN2Z0fWO8SqVls3H+2mm+DZiwl2kYg2ndMC9KkL317hZeb6F
    32o+51tqu2vv2051pTyzIIBIYoArV4cYplemYMPA8iNInqXB+wi/G4H2T+pXkz16
    Fdvsy7CxBu6sCTxqwk9CTRgbSFtpzOcihP0pjCN8tN84+YJ9ceGOEb/DF4EjKoSH
    AzGvEtlHH1N1D2a2LJUeUO7Cw/auMlktZOHg2IIM+ZNgm8OeNK7Nr6iiutN3klHC
    HG+njrNgOzRAc9aVrLNv7FtyBlFbp87PbP0sNBNcrtD1HhY767TWlC/+CC4gSmpK
    m3ZfgSkCgYEA0cND4pEP1eUQP4+6ZDyPN7j+fIQZgMK4ERYqy4KcoSFwMV0FziFE
    wEeDmjLMUZL2oiKz2+P/MdwYsSaR8Rhts/0Dlxz13XsRfTNvqNmgfhXH6g6k7kq8
    aMKbuBLiQop1roWOn5K2eg9/nq6gt3BOpAzR6xovLQffccO8HZHisu8CgYEA9LuS
    kjygzG/1cwpjtJb7vg1/KuKRiIBdWrmS6dh18KKd10YlDp4oPcW8ZG+jAY8Dce5c
    /pG9fTif2im8LsLQNk1t9ZKU3csTDUSe5AFuB/QR3c1Ighz2R13tiUKcOGxtzCGX
    ybA9wfpcmZkRRLr2JTIhl4gnxl0lPaoY4arWGS0CgYEApQ1wrSZXv4auclU15QmB
    5+a42GFZb+fHzioTIm9zr5YQIceAeeHTpzieZQbznnx1dL65p5yPgTweccZXr835
    BFdiK9Wt4Milyk5e3g3gK1YYKCO9w4MrHYOD5CN3xcQNNXYB864Nx53KXaIq9Cx6
    tLshsky4Mkavm2TY8KuKJiECgYAp4Tto2QUvVu1q3VlImxnDYS3k2dbLxCO1ldIl
    QEyWfE2EfFV1Fe2O/JqLmWsMpjuRsJerXKdPmXQJcmDoo5/b2w45GvdsqQa+m4KR
    RAlfRQ4Vpb6FvY0Lk3BFr+dp5Gw5pXoDIqy+2CgmhMImv9PFc7m546vizyfDUKtn
    WsO+lQKBgHzkw0KAv1iLW6A/kcZfXhEsVf9SALxzNM8o7YQoL1yFvSr+7a9fMXPI
    kGFFL3iYigS4CdG+yIrItlFxCqMJ9EnMgpMq5s9U9JUGqoUnCW9OEsm5G5X8UutY
    +wgWdsKcwO6xGCnH/KwWfJcmlivcNVOuMV8ykPSG4ryEKUUS59aX
    -----END RSA PRIVATE KEY-----
  max_upload_size: 10485760
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  expected_clients: 10000
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
Datastore:
  implementation: FileBaseDataStore
  location: /var/tmp/velociraptor
  filestore_directory: /var/tmp/velociraptor
Writeback: {}
Mail: {}
Logging: {}
Monitoring:
  bind_address: 10.100.1.5
  bind_port: 8003
api_config: {}
obfuscation_nonce: 9tQ3fLgHdvw=
